default: &default
  adapter: postgresql
  # encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Maintenance database: postgres
  # username: postgres
  # password: 12@34
  # host: localhost
  # port: 5432

development:
  <<: *default
  database: lemon_backend
  adapter: postgresql
  encoding: unicode
  port: 4556
  host: localhost
  username: postgres
  password: meshu
test:
  <<: *default
  database: lemon_test_backend
  adapter: postgresql
  encoding: unicode
  port: 4556
  host: localhost
  username: postgres
  password: meshu

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: hotel_production
  username: hotel
  password: <%= ENV["hotel_DATABASE_PASSWORD"] %>

